### PR TITLE
feat(changes): accept continuation token as a command line argument, display last token

### LINKED ISSUE #98: Read Changes command should output and take in continuation token
The read changes command should output and allow continuation token to be specified.  Otherwise, future changes will require starting from the beginning.

### PR DESCRIPTION
**Pull request by ewanharris**
## Description

This PR adds a `--continuation-token` flag to the `fga tuple changes` command to allow passing a continuation token that was provided by the FGA server. It also now logs the last retrieved continuation token alongside the changes output

<details>
<summary>Sample output</summary>

```
fga tuple changes --store-id 01HKMFHMD00Z298PFBT848K1N0
{
  "changes": [
    {
      "operation":"TUPLE_OPERATION_WRITE",
      "timestamp":"2024-01-08T12:08:01.312914916Z",
      "tuple_key": {
        "object":"group:foo",
        "relation":"member",
        "user":"user:anne"
      }
    },
    {
      "operation":"TUPLE_OPERATION_DELETE",
      "timestamp":"2024-01-08T12:10:21.524092718Z",
      "tuple_key": {
        "object":"group:foo",
        "relation":"member",
        "user":"user:anne"
      }
    },
    {
      "operation":"TUPLE_OPERATION_WRITE",
      "timestamp":"2024-01-08T12:10:29.012827054Z",
      "tuple_key": {
        "object":"group:bar",
        "relation":"member",
        "user":"user:bob"
      }
    }
  ],
  "continuation_token":"M3w="
}
fga tuple changes --store-id 01HKMFHMD00Z298PFBT848K1N0 --continuation-token M3w=
{
  "changes": [],
  "continuation_token":"M3w="
}
fga tuple changes --store-id 01HKMFHMD00Z298PFBT848K1N0 --continuation-token M3w=
{
  "changes": [
    {
      "operation":"TUPLE_OPERATION_DELETE",
      "timestamp":"2024-01-08T14:29:14.638373214Z",
      "tuple_key": {
        "object":"group:bar",
        "relation":"member",
        "user":"user:bob"
      }
    }
  ],
  "continuation_token":"NHw="
}
```

</details>

## References

Closes #98 

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [x] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by rhamzeh** [comment]
@aaguiarz are we still holding off on doing this or are you OK with merging it?

**Comment by aaguiarz** [comment]
@rhamzeh are we dispaying the continuation token? If so, I don't see a reason why not to do this. We could have another CLI option that polls and keeps outputing changes, but this one would not hurt.

**Comment by ewanharris** [comment]
@aaguiarz Yeah the JSON output now includes the continuation token returned from the API so folks can use it, sample output below
```
fga tuple changes --store-id 01HKMFHMD00Z298PFBT848K1N0 --continuation-token M3w=
{
  "changes": [
    {
      "operation":"TUPLE_OPERATION_DELETE",
      "timestamp":"2024-01-08T14:29:14.638373214Z",
      "tuple_key": {
        "object":"group:bar",
        "relation":"member",
        "user":"user:bob"
      }
    }
  ],
  "continuation_token":"NHw="
}
```

**Comment by aaguiarz** [comment]
We should update the output of the command in the readme, as it's now showing the continuation_token

 https://github.com/openfga/cli?tab=readme-ov-file#read-relationship-tuple-changes-watch

**Comment by aaguiarz** [comment]
We should update the readme with the new parameter as part of this PR too :)

**Review by rhamzeh — APPROVED** [review]

**Pull request merged**
