### PR TITLE
feat: Support exporting tuples in CSV, YAML and JSON format

### LINKED ISSUE #214: Support exporting tuples in CSV format
Follow up on https://github.com/openfga/cli/issues/206

We should replace `--simple-output` for read with `--output-format` 

In read, it should accept:
- `json`: default
- `yaml`
- `simple-json`: what `--simple-output` does currently
- `csv`

### PR DESCRIPTION
**Pull request by edwin-Marrima**
Closes #214 

## Description
Support exporting tuples in:
- csv
- yaml
- json: `default`

The CSV export fields align with those utilized during the import procedure, as detailed( https://github.com/openfga/cli/issues/206).

## References

related: https://github.com/openfga/cli/issues/206

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by rhamzeh** [comment]
Thanks for your PR @edwin-Marrima! We'll be reviewing it later in the day today

**Comment by rhamzeh** [comment]
@edwin-Marrima sorry for being late in the review. We were struggling with the idea of importing a dependency to deal with CSV, but ultimately decided that it is worth it.

The code overall looks 👍🏽, there are some changes around deprecating `--simple-output` and replacing it with `--output-format=simple-json`, but we can do that in a follow up PR

Before we merge, may I ask you to:
1. Address the lint issues? (`make format` and `male lint` would help)
2. Once done, squash your commits into one called: `feat: Support exporting tuples in CSV, YAML and JSON format`

Thanks again for your PR! ❤️

**Comment by edwin-Marrima** [comment]
@rhamzeh The rationale for retaining `--simple-output` is to facilitate straightforward output in various data formats such as CSV, YAML, and more. However, deprecating `--simple-output` and introducing `--output-format=simple-json` necessitates using additional flags/values like `--output-format=simple-csv` or `--output-format=simple-yaml` to achieve simple output in other formats. What do you think about?

**Comment by rhamzeh** [comment]
> @rhamzeh The rationale for retaining `--simple-output` is to facilitate straightforward output in various data formats such as CSV, YAML, and more. However, deprecating `--simple-output` and introducing `--output-format=simple-json` necessitates using additional flags/values like `--output-format=simple-csv` or `--output-format=simple-yaml` to achieve simple output in other formats. What do you think about?

Sorry for the late reply!

The idea is that only json has a need for a simple option, we use it so that the output can be used as the input of subsequent writes, the other formats don't need a simple option

So having
```
- json
- yaml
- csv
- simple-json
```

would work

**Comment by edwin-Marrima** [comment]
@rhamzeh I'm still facing the error: 'import 'github.com/gocarina/gocsv' is not allowed from list 'main' (depguard)'. Could you please update the '?depguard' file? I seem to be unable to locate it. Apart from that, everything else has been sorted out.

**Comment by rhamzeh** [comment]
If you can't, we'll get to it on Monday, thanks!

**Comment by edwin-Marrima** [comment]
> You just need to add it to the golinter file here: https://github.com/openfga/cli/blob/main/.golangci.yaml#L35-L49

Thank you, Solved.

**Review by rhamzeh — APPROVED** [review]

**Review by evansims — APPROVED** [review]

**Comment by rhamzeh** [comment]
Thanks for the PR @edwin-Marrima!

**Pull request merged**
