### PR TITLE
feat(tuple import): csv optional fields and support any columns order

### LINKED ISSUE #206: Import tuples from a csv
Hello,

We have a private tool to massively import tuples for a given relation from a csv file.

Our use case: 
When migrating permissions from a legacy system to openfga, we need to import all existing permissions as openfga relations. Legacy permissions are exported from the system database as a csv file.
The csv is expected to have 2 columns, the first being the user id and the second the object id. The command has mandatory options to specify the user type, the relation and the object type (In addition to common target server/auth/store related options).

Example
```
cli import-tuples <common options> --user-type user --relation administrator --object-type organization organizations_administrators.csv
```

The command batches the tuples import  (batch size is configurable with an option). 
All failling batches imports are written to a "failed" csv having the same structure as the input one (so it can be re-used as input itself).

Is it something you would be interested in?

Regards,
Yann

### PR DESCRIPTION
**Pull request by le-yams**
## Description
In csv tuple import, making the following fields optional:
 * `user_relation`
 * `condition_name`
 * `condition_context`

Also it supports any columns ordering now.

## References
closes #206 

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [x] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by le-yams** [comment]
I opened the PR as a draft as it's missing a check for the `condition_name` and `condition_context` (can't defined only one of them, both must be present or absent).

**Comment by le-yams** [comment]
> I opened the PR as a draft as it's missing a check for the `condition_name` and `condition_context` (can't defined only one of them, both must be present or absent).

Thinking about it, is it really true?
The condition name becomes mandatory if the the condition_context header is present but the condition context can be empty thus the field is optional even if the condition_name header is present isn't it?

**Comment by le-yams** [comment]
> The condition name becomes mandatory if the the condition_context header is present but the condition context can be empty thus the field is optional even if the condition_name header is present isn't it?

I've added a commit implementing this behavior

**Review by rhamzeh — DISMISSED** [review]
@le-yams looks good to me!

**Review by rhamzeh — APPROVED** [review]

**Comment by le-yams** [comment]
@rhamzeh thank you for the review and fixes 😃

**Review by ewanharris — APPROVED** [review]

**Pull request merged**
