### PR TITLE
feat(test): add support for asserting the excluded users

### PR DESCRIPTION
**Pull request by ewanharris**
## Description

Pulls in openfga v1.5.4 and some other dependency bumps, both `list_users` tests in the examples directory work as expected post upgrade:

```
cli % fga model test --tests ./example/model.fga.yaml     
# Test Summary #
Tests 1/1 passing
Checks 9/9 passing
ListObjects 6/6 passing
ListUsers 2/2 passing
cli % fga model test --tests ./example/store_abac.fga.yaml 
# Test Summary #
Tests 1/1 passing
Checks 3/3 passing
ListObjects 3/3 passing
ListUsers 2/2 passing
```

Excluded users support based on the example [here](https://openfga.dev/docs/getting-started/perform-list-users#excluded-users)

<details>

<summary>store file</summary>

```
model: | 
  model
    schema 1.1

  type user

  type document
    relations
      define viewer: [user:*] but not blocked
      define blocked: [user]
tuples:
  - user: user:*
    relation: viewer
    object: document:1
  - user: user:anne
    relation: blocked
    object: document:1
tests:
  - name: test
    list_users:
    - object: document:1
      user_filter:
        - type: user
      assertions:
        viewer:
          users:
            - user:*
          excluded_users:
            - user:anne
```

</details>

```
## Passing
cli % fga model test --tests ./store.fga.yaml
# Test Summary #
Tests 1/1 passing
ListUsers 1/1 passing

## Failure output
cli % fga model test --tests ./store.fga.yaml
(FAILING) test: ListUsers(0/1 passing)
ⅹ ListUsers(object={Type:document Id:1},relation=viewer,user_filter={Type:user Relation:<nil>}): expected={Users:[user:*] ExcludedUsers:[]}, got={Users:[user:*] ExcludedUsers:[user:anne]}
---
# Test Summary #
Tests 0/1 passing
ListUsers 0/1 passing
```

## Review Checklist
- [x] I have clicked on ["allow edits by maintainers"](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork).
- [ ] I have added documentation for new/changed functionality in this PR or in a PR to [openfga.dev](https://github.com/openfga/openfga.dev) [Provide a link to any relevant PRs in the references section above]
- [x] The correct base branch is being used, if not `main`
- [ ] I have added tests to validate that the change in functionality is working as expected

### CODE REVIEW

**Comment by rhamzeh** [comment]
Can you include these changes: https://github.com/openfga/openfga/pull/1653

**Comment by ewanharris** [comment]
@rhamzeh we don't perform any form of slsa verification in the release workflow for this repo currently

**Comment by rhamzeh** [comment]
Maybe we should copy over all this chunk: https://github.com/openfga/openfga/blob/f8505ce62c4cc0c882755e7bf21e3f8e0c8278d5/.github/workflows/release.yaml#L68-L198?

**Comment by ewanharris** [comment]
@rhamzeh I overlooked that this needs changes to finish off the excluded users support, I propose we handle slsa verification in a separate PR

**Comment by rhamzeh** [comment]
Sorry I thought this was the release PR, yeah def those should be a separate PR

**Review by rhamzeh — APPROVED** [review]

**Pull request merged**
