### PR TITLE
chore: simplify test output

### PR DESCRIPTION
**Pull request by tochev**
## Description
Simplify test output as outlined in https://github.com/openfga/cli/issues/251

## References
Closes https://github.com/openfga/cli/issues/251

## Sample output

I would be happy to change the output/code to suit what you prefer.

```
$ ./dist/fga model test --tests tests.fga.yaml
(FAILING) test-1: Checks (2/3 passing) | ListObjects (2/2 passing)
ⅹ Check(user=user:anne,relation=can_share,object=folder:1, context=<nil>): expected=false, got=true, error=<nil>
---
(FAILING) test-1b: Checks (2/3 passing) | ListObjects (1/2 passing)
ⅹ Check(user=user:anne,relation=can_share,object=folder:1, context=<nil>): expected=false, got=true, error=<nil>
ⅹ ListObjects(user=user:anne,relation=can_view,type=folder, context=<nil>): expected=[folder:2], got=[folder:1 folder:2], error=<nil>
---

# Test Summary #
Tests 2/4 passing
Checks 5/7 passing
ListObjects 6/7 passing
```

### CODE REVIEW

**Comment by rhamzeh** [comment]
Thanks for the PR @tochev - it looks all good from our end. There's a few lint issues pending (you can run `make lint` locally), if you have no bandwidth to resolve them in the next few days, no worries. We can get those fixed and merged

**Comment by tochev** [comment]
@rhamzeh , I fixed the linting of the file that I've touched, but there are other linting errors as well. Should I change the other files as well?

**Comment by rhamzeh** [comment]
> @rhamzeh , I fixed the linting of the file that I've touched, but there are other linting errors as well. Should I change the other files as well?

It's OK - apologies about that, looks like new golintci rules are in effect and your PR got caught in the crossfire :)

**Review by rhamzeh — APPROVED** [review]

**Comment by rhamzeh** [comment]
Ah we'll need another reviewer now 😅

**Review by jimmyjames — APPROVED** [review]

**Comment by rhamzeh** [comment]
Thanks for this PR @tochev!

**Pull request merged**
